[package]
name = "gaemdev_001"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12"
bevy_pixel_camera = "0.5.0"
bevy_rapier2d = "0.23.0"
